### ISSUE TITLE
Labeling Sampson data

### ISSUE THREAD

**Issue by zpneal** [schochastics/networkdata#10]
It's a little unclear which sampson matrix is which. By comparison with other versions of these data, I think it's in this order: SAMPLK1, SAMPLK2, SAMPLK3, SAMPDLK, SAMPES, SAMDES, SAMPIN, SAMNIN, SAMPPR, SAMNPR. To avoid ambiguity, it might be helpful to include these as graph attributes.

**Comment by schochastics** [comment]
hmm thought I added a name attribute to the graph which I apparently didnt do. I think I will replace the dataset with another version including names before I am guessing wrong here. Thanks for pointing it out
