### ISSUE TITLE
Glitches

### ISSUE THREAD

**Issue by mbojan** [schochastics/networkdata#4]
@schochastics , I have a small army of students doing lab projects on various data sets from the package. We are finding various small glitches in data and documentation. For example `animal_34` should be an igraph object but it is a list of length 1 with that object, and so on...

Would you prefer PRs and fix such things in the package, or perhaps you have some scripts that process the original data files outside of the package and you'd rather address such things there? In the case of the latter I'd just create issues. What would you prefer?

**Comment by schochastics** [comment]
@mbojan 
I think I'd prefer issues, so that I can fix the background scripts.
But if a PR is easier for you, then I am more than happy with that too.
So, it is mostly up to you.

In any case, thanks for this. Clearly, the automatic approach has some drawbacks ;-)

**Comment by mbojan** [comment]
> I think I'd prefer issues, so that I can fix the background scripts.
> But if a PR is easier for you, then I am more than happy with that too.
> So, it is mostly up to you.

OK, issues then.


> In any case, thanks for this. Clearly, the automatic approach has some drawbacks ;-)

Yeah... I guess you could keep all the source files within repo in `data-raw` but all of them in LFS (https://git-lfs.github.com/). I used it very successfully in other projects.
