### ISSUE TITLE
dataset movie_439 typo in actor name

### ISSUE THREAD

**Issue by dirusulixes** [schochastics/networkdata#6]
Hi there, 
A small typo I think
`V(movie_439)$name[8:9]`
`[1] "FRO DO" "FRODO"`

**Comment by dirusulixes** [comment]
I dug a bit deeper, and the typo is actually in the script as reported here: https://imsdb.com/scripts/Lord-of-the-Rings-Fellowship-of-the-Ring,-The.html 
In case it makes a difference.

**Comment by schochastics** [comment]
thanks for digging this up. Gonna fix it immediately.
