### ISSUE TITLE
French Financial Elite networks are not right

### ISSUE THREAD

**Issue by stivalaa** [schochastics/networkdata#7]
David,

Thanks for writing/maintaining this package, I've found it incredibly useful.

However there seems to be some problem with the French Financial Elite (ffe_friendship specifically, but also ffe_influence and ffe_elite) networks. The ffe_friendship network is clearly not right, it is far denser than it should be, and has loops (self-edges) on some (not all) nodes. The other two also don't seem right.

I compared the data to the original UCINET DL files from Linton C. Freeman's website (no longer available, but I kept a copy before it went offline), and something has clearly gone wrong in the conversion: the original matches the relevant paper (Kadushin, 1995). Also the older  R version of these data from Zack Almquist https://github.com/zalmquist/networkdata are correct. (It is hard to reliably read UCINET files directly in R, I checked by just manually cutting & pasting adjacency matrices from the Freeman data, and compared these to what is published in Kadushin (1995) and to the .rds file from Zack Almquist's repository).

So something seems to have gone wrong in the conversion process here. It seems it might be specific to these networks, as I checked the Lazega lawfirm data (speficially law_friends) and it appears correct, even though, like the French financial elite data, there are three network layers.

Regards,
Alex.

**Comment by schochastics** [comment]
Thanks for finding this. I indeed did all the conversion semi automatic and that didnt go too well with a lot of UCINET data. I will correct this

**Comment by schochastics** [comment]
@stivalaa could you just clarify what you mean by "three network layers"? law_friends should just be a directed graph and the other relations are in law_cowork, law_advice.

**Comment by stivalaa** [comment]
@schochastics Thanks for fixing this up. By "three network layers" in the Lazega law firm data, I just meant the fact that in the original Freeman UCINET DL data, the three networks (advice, friendship, cowork) are just present one directly after the other as adjacency matrices, just as the French Financial Elite data are.  The 3 networks are referred to as "layers" in the UCINET DL data format - but are just the 3 separate igraph objects law_advice, law_friends and law_cowork in networkdata)

The difference that caused the problem in the financial elites but not the law firm data might be that the financial elites data have node labels in the .dat file, and the law firm data do not; this is difference I just noticed.
