### ISSUE TITLE
Can't find function "show_networks"

### ISSUE THREAD

**Issue by cc50liu** [schochastics/networkdata#8]
When I call

<code>show_networks(type = "directed")</code>

I receive

<code>Error in show_networks() : could not find function "show_networks"</code>

despite the fact that I have installed networkdata and called <code>library(networkdata)</code>.  If I call

<code>networkdata::show_networks()</code>

I receive

<code>Error: 'show_networks' is not an exported object from 'namespace:networkdata'</code>

Any suggestions for how to work around this?

**Comment by schochastics** [comment]
I removed the function a while back nut apparently there was some residue code left. The function should now completely gone. I will add it back in an upcoming release when I have fixed some issues with it.
