### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by jdfoote** [schochastics/networkdata#9]
I just upgraded to R 4.2.0, and when I tried to install with:

`remotes::install_github("schochastics/networkdata")`

I got the following error:

```
Error: Failed to install 'networkdata' from GitHub:
  Multiple results for CXXFLAGS found, something is wrong.FALSE
```

Is this a problem on my end?

**Comment by schochastics** [comment]
This might be an issue on your end because the package doe not depend on any C or C++ code. Maybe this helps:
https://github.com/stan-dev/rstan/issues/866

**Comment by jdfoote** [comment]
Thank you very, very much!

I did not think that I had a `Makevars` file, but apparently I did, and it was broken. :)
